


jobeet_platform:
    resource: "@JOBEETPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform


login:
    path: /login
    defaults:
        _controller: JOBEETUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout