

jobeet_platform_home:
    path:      /platform
    defaults: { _controller: JOBEETPlatformBundle:Advert:index }
    
jobeet_platform_view:
    path:      /platform/advert/{id}
    defaults: { _controller: JOBEETPlatformBundle:Advert:view }
    
jobeet_platform_add:
    path:      /platform/add
    defaults: { _controller: JOBEETPlatformBundle:Advert:add }

jobeet_platform_view_slug:
    path:      /platform/{year}/{slug}.{format}
    defaults:
        _controller: JOBEETPlatformBundle:Advert:viewSlug
        format:      html
    requirements:
        year:   \d{4}
        format: html|xml
