
jobeet_platform_home:
    path:      /{page}
    defaults:
        _controller: JOBEETPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

jobeet_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: JOBEETPlatformBundle:Advert:view
    requirements:
        id: \d+

jobeet_platform_add:
    path:      /add
    defaults:
        _controller: JOBEETPlatformBundle:Advert:add

jobeet_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: JOBEETPlatformBundle:Advert:edit
    requirements:
        id: \d+

jobeet_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: JOBEETPlatformBundle:Advert:delete
    requirements:
        id: \d+
